name: Code Quality Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy black pytest

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Check typing with mypy
        run: |
          mypy .

      - name: Check formatting with black
        run: |
          black --check .

      - name: Run tests
        run: |
          pytest
